
import httpx, hashlib, os, uuid, secrets, hmac, json, time, cv2, numpy as np, mediapipe as mp, asyncio, base64, logging

from dotenv import load_dotenv
from fastapi import FastAPI, File, UploadFile, HTTPException, Depends, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security.api_key import APIKeyHeader
from pydantic import BaseModel, EmailStr
from supabase import create_client, Client, AuthApiError
from starlette.requests import Request
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
from datetime import datetime, timezone
from openai import AsyncOpenAI

# security
MIN_FILE_SIZE = 10 * 1024 # 10 KB (trash)
MAX_FILE_SIZE = 5 * 1024 * 1024  # 5 MB
ALLOWED_MIME_TYPES = ["image/jpeg", "image/png", "image/webp"]
ALLOWED_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}

# rate limiting
# araayüz gezintisi için rate limiting
MGMT_RATE_LIMIT_STORAGE = {}
MGMT_LIMIT_PER_MINUTE = 120

# Auth işlemleri için IP bazlı limit (Dakikada 5 deneme)
AUTH_RATE_LIMIT_STORAGE = {}
AUTH_LIMIT_PER_MINUTE = 5

# RATE_LIMIT_STORAGE ve AUTH_RATE_LIMIT_STORAGE in-memory çalışıyor. Tek bir worker ile bu durum sorun yaratmaz.
# Eğer ileride sunucuda birden fazla worker çalışacaksa her workerin kendi belleği olacağından Redis entegrasyonu yapılmalıdır.
RATE_LIMIT_STORAGE = {}
RATE_LIMIT_LOCK = asyncio.Lock()
PACKAGE_LIMITS = { # rate limit / second for packages
    "free": 1,
    "lite": 1,
    "pro": 1
}
PACKAGE_LIMITS_MINUTE = { # rate limit / minute for packages
    "free": 5,
    "lite": 20,
    "pro": 60
}

# credits
# monthly limit
MONTHLY_LIMITS = {
    "free": 50,
    "lite": 500,
    "pro": 2000
}
# daily limit
DAILY_LIMITS = {
    "free": 10,
    "lite": 75,
    "pro": 300
}

# key limits
PLAN_KEY_LIMITS = {
    "free": 1,
    "lite": 2,
    "pro": 5
}

# business package default limits, theese used if data not fount at database
DEFAULT_BUSINESS_PACKAGE_RATE_LIMIT_SECOND = 5
DEFAULT_BUSINESS_PACKAGE_RATE_LIMIT_MINUTE = 120
DEFAULT_BUSINESS_PACKAGE_DAILY_CREDITS_LIMIT = 500
DEFAULT_BUSINESS_PACKAGE_MONTHLY_CREDITS_LIMIT = 5000
DEFAULT_BUSINESS_PACKAGE_MAX_LIVE_KEY_LIMIT = 20

# decision matrix
ANALYSIS_MAP = {
    "SEMANTIC_ANOMALY": {
        "label": "SEMANTIC_ANOMALY_DETECTION",
        "risk_level": "HIGH",
        "description": "Biological or logical inconsistencies (e.g., impossible hybrids or structural anomalies) detected in the content.",
        "recommendation": {
            "action": "REJECT",
            "message": "High security risk. The content contains logical or biological anomalies that do not exist in reality. Rejection is strongly recommended."
        }
    },
    "DEEPFAKE": {
        "label": "DEEPFAKE_DETECTION",
        "risk_level": "HIGH",
        "description": "High probability of synthetic face swap or digital identity manipulation detected.",
        "recommendation": {
            "action": "REJECT",
            "message": "High security risk. A synthetic face swap or identity manipulation was detected. Rejecting the photo is recommended."
        }
    },
    "SYNTHETIC": {
        "label": "SYNTHETIC_CONTENT",
        "risk_level": "HIGH",
        "description": "High probability that the identity or image is entirely generated by artificial intelligence.",
        "recommendation": {
            "action": "REJECT",
            "message": "High security risk. This image appears to be entirely AI-generated. Manual review is recommended."
        }
    },
    "MODIFIED": {
        "label": "MODIFIED_CONTENT",
        "risk_level": "MEDIUM",
        "description": "Significant digital retouching, heavy filters, or background manipulation detected. The core identity appears intact.",
        "recommendation": {
            "action": "REVIEW",
            "message": "Significant digital retouching or heavy filters detected. Manual verification or a raw photo request is recommended."
        }
    },
    "INCONCLUSIVE": {
        "label": "INCONCLUSIVE",
        "risk_level": "MEDIUM",
        "description": "Image quality, compression, or file structure is insufficient for a conclusive authenticity analysis.",
        "recommendation": {
            "action": "REVIEW",
            "message": "Image quality or file structure is insufficient for a conclusive analysis. Request a high-resolution photo taken directly from the camera."
        }
    },
    "AUTHENTIC": {
        "label": "AUTHENTIC",
        "risk_level": "LOW",
        "description": "No synthetic face swap or fully AI-generated identity was detected.",
        "recommendation": {
            "action": "ACCEPT",
            "message": "The image meets authenticity standards. No AI-generated or deepfake manipulation was detected."
        }
    }
}

VLM_EXPLANATION_MAP = {
    # BIOLOGICAL_ANOMALY (Biyolojik Anomali):
    # - İnsan anatomisine aykırı durumlar (Örn: 6 parmaklı eller, asimetrik göz bebekleri).
    # - Türler arası imkansız melezler (Örn: Kedi kafasına sahip insan vücudu).
    # - Fizyolojik olarak imkansız vücut duruşları veya eksik/fazla uzuvlar.
    "BIOLOGICAL_ANOMALY": "anatomical impossibilities or improper biological structures",

    # PHYSICAL_INCONSISTENCY (Fiziksel Tutarsızlık):
    # - Işık ve gölge hataları (Örn: Işık sağdan vururken gölgenin sağa düşmesi).
    # - Yerçekimine veya fizik kurallarına aykırı duran objeler (Örn: Havada asılı kalan veya yüzeye temas etmeyen eşyalar).
    # - Aynadaki yansımanın kişiyle veya ortamla uyuşmaması.
    "PHYSICAL_INCONSISTENCY": "physical inconsistencies such as gravity, lighting, or reflection errors",

    # DELIBERATE_OBSCURATION (Kasten Gizleme/Bulanıklaştırma):
    # - Bir manipülasyonu (Photoshop hatasını veya AI izini) saklamak için fotoğrafın belli bir yerine kasten eklenmiş aşırı kirlilik (noise) veya bulanıklık (blur).
    # - Yüzün veya kimlik kartı gibi kritik bölgelerin üzerine "yanlışlıkla" düşmüş gibi duran ama aslında iz kapatan büyük piksellenmeler.     
    "DELIBERATE_OBSCURATION": "deliberate obscuration or masking of details",

    # CONTEXTUAL_MISMATCH (Bağlamsal Uyumsuzluk):
    # - Fotoğraftaki ana obje ile arka planın uyumsuzluğu (Örn: Kışlık kalın bir mont giyen kişinin arkasında yazlık güneşli bir kumsal olması).
    # - Objelerin birbirine göre orantısız büyüklükte olması (Örn: Bir kedinin arka plandaki arabadan daha büyük görünmesi).
    # - Arka planın kes-yapıştır (crop) yapıldığını belli eden keskin kenar izleri.  
    "CONTEXTUAL_MISMATCH": "contextual or proportional mismatches between subjects and the background",

    # SYNTHETIC_ARTIFACTS (Sentetik Kalıntılar/İzler):
    # - Midjourney, DALL-E gibi yapay zeka modellerinin sıklıkla yaptığı tipik doku (texture) hataları.
    # - Anlamsız erimiş yazılar (AI genelde metinleri doğru üretemez ve harfler birbirine girer).
    # - Saç tellerinin cilde veya kıyafete doğal olmayan bir şekilde yapışıp "erimiş" gibi durması.
    "SYNTHETIC_ARTIFACTS": "AI-specific texture artifacts and hallucinations"
}

app = FastAPI(title="api.cludek.com", version="1.0.0")

load_dotenv()

# logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
logger.propagate = False
formatter = logging.Formatter("[%(levelname)s] - %(asctime)s - %(name)s - %(message)s")

# console logger for development and debugging
console_handler = logging.StreamHandler()
console_handler.setFormatter(formatter)
if logger.hasHandlers():
    logger.handlers.clear()
logger.addHandler(console_handler)
logger.info("action=logger_init | status=render_logs_ready")

openai_client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# cors
origins = [
    "https://cludek.com",
    "http://localhost:5173",  # vide default port
    "http://127.0.0.1:5173",
    "http://localhost:3000",  # other development ports
]
app.add_middleware(CORSMiddleware, allow_origins=origins, allow_credentials=True, allow_methods=["*"], allow_headers=["*"])

# Sightengine cradentials
SIGHTENGINE_USER = os.getenv("SIGHTENGINE_USER")
SIGHTENGINE_SECRET = os.getenv("SIGHTENGINE_SECRET")
API_URL = os.getenv("API_URL")

# Supabase cradentials
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# authentication (b2b priority)
security = HTTPBearer(auto_error=False)
api_key_header = APIKeyHeader(name="X-API-KEY", auto_error=False)

# global http client
http_client = httpx.AsyncClient(
    http2=False, # Kararlılık için HTTP/1.1
    limits=httpx.Limits(max_keepalive_connections=10, max_connections=20),
    timeout=httpx.Timeout(10.0)
)

# tflite modeli yolu
MODEL_PATH = 'blaze_face_short_range.tflite'

# start the model globally
try:
    base_options = python.BaseOptions(model_asset_path=MODEL_PATH)
    options = vision.FaceDetectorOptions(
        base_options=base_options, 
        min_detection_confidence=0.5
    )
    face_detector = vision.FaceDetector.create_from_options(options)
    logger.info("action=model_load | model=mediapipe_face_detector | status=success")
except Exception as e:
    logger.critical(f"action=model_load | model=mediapipe_face_detector | status=failure | error={str(e)}", exc_info=True)
    raise RuntimeError(f"Model load failure: {e}")

async def log_failed_request_to_db(user_id: str, request_id: str, endpoint: str, error_code: str, message: str):
    """Kullanıcının iş akışını bozan mantıksal hataları (Business Logic) DB'ye kaydeder."""
    try:
        await asyncio.to_thread(
            lambda: supabase.table("failed_requests_log").insert({
                "user_id": user_id,
                "request_id": request_id,
                "endpoint": endpoint,
                "error_code": error_code,
                "message": message
            }).execute()
        )
    except Exception as e:
        # Loglama işleminin kendisi hata verirse sistemi çökertmez, sadece CloudWatch'a yazar.
        logger.error(f"action=db_log_failed | request_id={request_id} | error={str(e)}")

async def call_vlm(image_content: bytes) -> dict:
    """
        GPT-4o (veya Vision destekli başka bir model) kullanarak gerçek VLM analizi yapar.
        Sadece istenen JSON formatında yanıt dönmeye zorlanmıştır.
    """
    # 1. Byte verisini Base64'e çevir
    base64_image = base64.b64encode(image_content).decode('utf-8')
    
    # 2. VLM için katı kurallı System Prompt
    system_prompt = """
    You are an expert forensic image analysis AI. Your task is to detect semantic and logical anomalies that indicate an image is a deepfake or AI-generated.
    Score the following 5 categories from 0.0 (perfectly authentic) to 100.0 (definitely anomalous/fake).
    You MUST return ONLY a valid JSON object with exact following keys and float values:
    {
        "biological_anomaly": float,
        "physical_inconsistency": float,
        "deliberate_obscuration": float,
        "contextual_mismatch": float,
        "synthetic_artifacts": float
    }
    """

    try:
        # 3. Asenkron API Çağrısı (response_format ile JSON garantisi)
        response = await openai_client.chat.completions.create(
            model="gpt-4o-mini", # Maliyet/Hız optimizasyonu için mini veya gpt-4o kullanabilirsin
            response_format={ "type": "json_object" },
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": [
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/jpeg;base64,{base64_image}",
                            "detail": "high" # Yüksek çözünürlüklü analiz için
                        }
                    }
                ]}
            ],
            max_tokens=200,
            temperature=0.0, # Sabit ve tutarlı skorlar için 0 (sıfır) olmalı
            timeout=15.0 # 15 saniyelik timeout, bu süre aşılırsa istisna fırlatır
        )
        
        # response
        usage = response.usage # prompt_tokens, completion_tokens, total_tokens içerir
        raw_json = response.choices[0].message.content
        sub_details = json.loads(raw_json)
        
    except Exception as e:
        logger.error("action=vlm_api_failed", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail={
                "code": "VLM_ANALYSIS_FAILED",
                "message": "Semantic analysis engine is temporarily unavailable."
            }
        )

    # filtreleme ve etiketleme mantığı
    reasons = [key.upper() for key, score in sub_details.items() if float(score) >= 80.0]
    total_score = max([float(v) for v in sub_details.values()])
    
    if not reasons:
        explanation = "No significant semantic anomalies detected. The image appears logically consistent."
    else:
        explanation_parts = [VLM_EXPLANATION_MAP[reason] for reason in reasons if reason in VLM_EXPLANATION_MAP]
        explanation = f"Analysis detected {', '.join(explanation_parts)}. These findings suggest a lack of semantic authenticity."

    return {
        "total_anomaly_score": total_score,
        "anomaly_reasons": reasons,
        "anomaly_explanation": explanation,
        "details": sub_details,
        "prompt_tokens": usage.prompt_tokens,
        "completion_tokens": usage.completion_tokens,
        "openai_request_id": response.id
    }

# quality control functions
def decode_image(image_bytes: bytes):
    nparr = np.frombuffer(image_bytes, np.uint8)
    return cv2.imdecode(nparr, cv2.IMREAD_COLOR)

def check_resolution(img_matrix, min_width=512, min_height=512) -> dict:
    height, width = img_matrix.shape[:2]
    if width < min_width or height < min_height:
        return {"is_valid": False, "error_code": "LOW_RESOLUTION", "message": f"Resolution too low ({width}x{height}). Minimum required is {min_width}x{min_height}."}
    return {"is_valid": True}

def check_blur(img_matrix, blur_threshold=35.0) -> dict:
    gray = cv2.cvtColor(img_matrix, cv2.COLOR_BGR2GRAY)
    variance = cv2.Laplacian(gray, cv2.CV_64F).var()
    if variance < blur_threshold:
        return {"is_valid": False, "error_code": "BLURRY_IMAGE", "message": "Image is too blurry for reliable analysis."}
    return {"is_valid": True}

def check_exposure(img_matrix, dark_thresh=20, bright_thresh=235) -> dict:
    gray = cv2.cvtColor(img_matrix, cv2.COLOR_BGR2GRAY)
    mean_brightness = np.mean(gray)
    if mean_brightness < dark_thresh:
        return {"is_valid": False, "error_code": "TOO_DARK", "message": "Image is too dark for analysis."}
    if mean_brightness > bright_thresh:
        return {"is_valid": False, "error_code": "TOO_BRIGHT", "message": "Image is overexposed."}
    return {"is_valid": True}

def validate_image_quality(img_matrix) -> dict:
    if img_matrix is None:
        return {"is_valid": False, "error_code": "UNPROCESSABLE_IMAGE", "message": "Image could not be decoded."}
        
    # çözünürlük
    res_check = check_resolution(img_matrix)
    if not res_check.get("is_valid"): return res_check
        
    # pozlama: karanlık ve parlaklık
    exp_check = check_exposure(img_matrix)
    if not exp_check.get("is_valid"): return exp_check
    
    # bulanıklık
    blur_check = check_blur(img_matrix)
    if not blur_check.get("is_valid"): return blur_check
        
    return {"is_valid": True, "error_code": None, "message": None}

async def check_human_face(img_matrix) -> dict:
    """
        Numpy 2.0+ ve en güncel MediaPipe sürümleriyle uyumlu, 
        'image_ptr' hatasını engelleyen modern implementasyon.
    """
    try:    
        # MediaPipe RGB formatı bekler
        img_rgb = cv2.cvtColor(img_matrix, cv2.COLOR_BGR2RGB)
        # KRİTİK ADIM: Numpy dizisinin hafıza düzenini (memory layout) zorla düzeltiyoruz
        # Bu satır, MediaPipe'ın beklediği C-style hafıza dizilimini garanti eder.
        img_rgb = np.ascontiguousarray(img_rgb)

        # MediaPipe Image objesini oluştur
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=img_rgb)
        
        # CPU bloklanmasını önlemek için asenkron thread kullan
        detection_result = await asyncio.to_thread(face_detector.detect, mp_image)
        print(detection_result) # debug için ekledim, kaldırabilirsin
        face_count = len(detection_result.detections) if detection_result.detections else 0

        if face_count == 0:
            return {"is_valid": False, "error_code": "FACE_NOT_DETECTED", "message": "No valid human face found in the image."}
        elif face_count > 1:
            return {"is_valid": False, "error_code": "MULTIPLE_FACES_DETECTED", "message": "Multiple faces detected. Please upload an image with a single person."}
            
        return {"is_valid": True, "error_code": None, "message": None}
        
    except Exception as e:
        logger.error("action=face_detection_engine_failed", exc_info=True)
        raise RuntimeError("Face detection engine failed") from e

async def get_auth_user(api_key: str = Depends(api_key_header), credentials: HTTPAuthorizationCredentials = Depends(security)):
    user_id = None
    auth_info = {}
    
    # API Key
    if api_key:
        api_key = api_key.strip()
        hashed_key = hashlib.sha256(api_key.encode()).hexdigest()

        # supabase sorgusunu ayrı bir thread ile yapıyoruz, böylece saniye bazlı rate limit uygulayabiliriz
        result = await asyncio.to_thread(
            lambda: supabase.table("api_keys").select("user_id").eq("key_hash", hashed_key).eq("is_active", True).execute()
        )

        if result.data:
            user_id = result.data[0]["user_id"]
            auth_info = {"id": user_id, "is_test": api_key.startswith("sk_test_"), "auth_type": "api_key"}
            logger.info(f"action=auth_success | auth_type=api_key | key_hash={hashed_key} | user_id={user_id}")
        else:
            logger.warning(f"action=auth_failed | reason=invalid_api_key | key_hash={hashed_key}")
            raise HTTPException(status_code=401, detail={"code": "INVALID_API_KEY", "message": "Invalid or inactive API key."})
    # JWT
    elif credentials:
        try:
            user_response = await asyncio.to_thread(
                lambda: supabase.auth.get_user(credentials.credentials)
            )

            if not user_response.user.email_confirmed_at:
                logger.warning(f"action=auth_failed | reason=email_not_confirmed | user_id={user_response.user.id}")
                raise HTTPException(
                    status_code=403, 
                    detail={"code": "EMAIL_NOT_CONFIRMED", "message": "Please confirm your email address to use the API."}
                )

            user_id = user_response.user.id
            auth_info = {"id": user_id, "is_test": False, "auth_type": "jwt", "provider": user_response.user.app_metadata.get("provider")}
            logger.info(f"action=auth_success | auth_type=jwt | user_id={user_id}")
        except Exception as e:
            logger.warning(f"action=auth_failed | reason=invalid_jwt | error={str(e)}")
            raise HTTPException(status_code=401, detail={"code": "INVALID_JWT", "message": "Invalid or expired token."})
    
    if user_id:
        # tüm profil verisi burada çekilip endpointlere dağıtılıyor
        profile_res = await asyncio.to_thread(
            lambda: supabase.table("profiles").select("*").eq("id", user_id).maybe_single().execute()
        )
        # profile_res objesi var mı ve hata içermiyor mu?
        if not profile_res or hasattr(profile_res, "error") and profile_res.error:
            logger.error(f"Supabase connection error for user {user_id}")
            raise HTTPException(status_code=500, detail={"code": "DATABASE_ERROR", "message": "Database connection failed."})
        
        # Veri (data) var mı? .data özelliği Supabase response'unda her zaman bulunur ama boşsa None döner.
        profile = getattr(profile_res, "data", None)

        if not profile:
            logger.error(f"action=auth_failed | reason=profile_missing | user_id={user_id}")
            raise HTTPException(
                status_code=404, 
                detail={"code": "PROFILE_NOT_FOUND", "message": "User profile not found."}
            )
        
        # waitlist check
        if not profile.get("is_allowed", False):
            logger.warning(f"action=auth_rejected | reason=waitlist | user_id={user_id}")
            raise HTTPException(
                status_code=403, 
                detail={"code": "WAITLIST_REQUIRED", "message": "You do not have access permissions yet."}
            )
        
        auth_info["profile"] = profile
        return auth_info

    # unauthorized
    logger.warning("action=auth_rejected | reason=unauthorized_request")
    raise HTTPException(status_code=401, detail={"code": "UNAUTHORIZED", "message": "Unauthorized request."})

# register ve login endpointleri için limiter
async def auth_rate_limiter(request: Request):
    ip = request.client.host
    async with RATE_LIMIT_LOCK:
        now = time.time()

        history = AUTH_RATE_LIMIT_STORAGE.get(ip, [])

        # 60 saniyeden eski kayıtları temizle
        history = [t for t in history if now - t < 60.0]

        if len(history) >= AUTH_LIMIT_PER_MINUTE:
            logger.warning(f"action=rate_limit_exceeded | type=auth_ip | ip={ip}")
            raise HTTPException(
                status_code=429, 
                detail={"code": "RATE_LIMIT_EXCEEDED", "message": "Too many attempts. Please try again in a minute."}
            )
            
        history.append(now)
        AUTH_RATE_LIMIT_STORAGE[ip] = history

# arayüz gezintisi için rate limiter
async def management_rate_limiter(auth = Depends(get_auth_user)):
    user_id = auth["id"]
    
    async with RATE_LIMIT_LOCK:
        now = time.time()

        history = MGMT_RATE_LIMIT_STORAGE.get(user_id, [])
        # Son 60 saniyeyi tut
        history = [t for t in history if now - t < 60.0]

        if len(history) >= MGMT_LIMIT_PER_MINUTE:
            logger.warning(f"action=rate_limit_exceeded | type=management | user_id={user_id}")
            raise HTTPException(
                status_code=429, 
                detail={"code": "RATE_LIMIT_EXCEEDED", "message": "Too many dashboard requests. Please slow down."}
            )
            
        history.append(now)
        MGMT_RATE_LIMIT_STORAGE[user_id] = history

    return auth

# planlara özel rate limiter
async def rate_limiter(auth = Depends(get_auth_user)):
    user_id = auth["id"]
    profile = auth["profile"]
    plan_type = profile.get("plan_type", "free")
    
    # 1. Limit Belirleme
    if plan_type == "business":
        sec_limit = profile.get("custom_rate_limit") or DEFAULT_BUSINESS_PACKAGE_RATE_LIMIT_SECOND
        minute_limit = profile.get("custom_rate_limit_min") or DEFAULT_BUSINESS_PACKAGE_RATE_LIMIT_MINUTE
    else:
        sec_limit = PACKAGE_LIMITS.get(plan_type, 1)
        minute_limit = PACKAGE_LIMITS_MINUTE.get(plan_type, 5)

    # 2. Limit Kontrolü
    async with RATE_LIMIT_LOCK:
        now = time.time()

        history = RATE_LIMIT_STORAGE.get(user_id, [])
        # Temizlik: 60 saniyeden eski tüm istekleri bellekten at
        history = [t for t in history if now - t < 60.0]

        # A. Saniyelik Kontrol (Son 1 saniye)
        requests_last_sec = [t for t in history if now - t < 1.0]
        if len(requests_last_sec) >= sec_limit:
            logger.warning(f"action=rate_limit_exceeded | type=api_second | limit={sec_limit} | user_id={user_id}")
            raise HTTPException(status_code=429, detail={"code": "RATE_LIMIT_EXCEEDED", "message": "Rate limit (seconds) exceeded."})
        
        # B. Dakikalık Kontrol (Son 60 saniye)
        if len(history) >= minute_limit:
            logger.warning(f"action=rate_limit_exceeded | type=api_minute | limit={minute_limit} | user_id={user_id}")
            raise HTTPException(status_code=429, detail={"code": "RATE_LIMIT_EXCEEDED", "message": f"Exceeded minute limit: ({minute_limit} req/min)."})
            
        # İstek başarılı, zaman damgasını ekle
        history.append(now)
        RATE_LIMIT_STORAGE[user_id] = history

    # Endpoint'in kullanması için auth datayı geri dön
    return auth

async def check_daily_limit(profile: dict, request_id: str = "N/A", endpoint: str = "N/A"):
    user_id = profile.get("id")
    daily_usage = profile.get("daily_usage", 0)
    last_reset_str = profile.get("last_daily_usage_reset")
    plan_type = profile.get("plan_type", "free")

    if plan_type == "business":
        daily_limit = profile.get("custom_daily_limit") or DEFAULT_BUSINESS_PACKAGE_DAILY_CREDITS_LIMIT
    else:
        daily_limit = DAILY_LIMITS.get(plan_type)

    now = datetime.now(timezone.utc)
    
    # 24 Saat Kontrolü ve Sıfırlama
    if not last_reset_str:
        last_reset_str = now.isoformat()
        
    last_reset = datetime.fromisoformat(last_reset_str.replace('Z', '+00:00'))
    
    if (now - last_reset).total_seconds() >= 86400:
        try:
            await asyncio.to_thread(
                lambda: supabase.table("profiles")
                .update({"daily_usage": 0, "last_daily_usage_reset": now.isoformat()})
                .eq("id", user_id).execute()
            )
            logger.info(f"action=daily_usage_reset_success | user_id={user_id} | previous_usage={daily_usage}")
            daily_usage = 0
        except Exception as e:
            logger.error(f"action=daily_usage_reset_failed | user_id={user_id}", exc_info=True)

    # Limit Aşım Kontrolü
    if daily_usage >= daily_limit:
        logger.warning(f"action=daily_limit_exceeded | limit={daily_limit} | user_id={user_id}")

        await log_failed_request_to_db(
            user_id=user_id, 
            request_id=request_id, 
            endpoint=endpoint, 
            error_code="DAILY_LIMIT_EXCEEDED", 
            message=f"Daily usage limit exceeded: max = {daily_limit}."
        )

        raise HTTPException(
            status_code=429, 
            detail={"code": "DAILY_LIMIT_EXCEEDED", "message": f"Daily usage limit exceeded: max = {daily_limit}."}
        )
    
    return daily_usage

# jwt
@app.post("/generate-api-key")
async def generate_api_key(name: str = "Default Key", key_type: str = "live", current_user = Depends(rate_limiter)):
    user_id = current_user["id"]

    if current_user.get("auth_type") == "api_key":
        logger.warning(f"action=api_key_generation_rejected | reason=invalid_auth_method | user_id={user_id}")
        raise HTTPException(status_code=403, detail={"code": "API_KEY_RESTRICTED", "message": "API keys cannot use for this endpoint. Please use jwt access."})

    # test key: max 1 for every user
    if key_type == "test":
        test_res = await asyncio.to_thread(
            lambda: supabase.table("api_keys").select("id", count="exact")
            .eq("user_id", user_id).like("key_hint", "sk_test_%").execute()
        )
        if (test_res.count or 0) >= 1:
            logger.warning(f"action=api_key_generation_rejected | reason=max_test_keys_exceeded | user_id={user_id}")
            raise HTTPException(status_code=403, detail={"code": "MAX_TEST_KEYS_EXCEEDED", "message": "Max allowed test key count = 1"})
    
    # live key
    else:
        profile_data = current_user.get("profile", {})
        plan_type = profile_data.get("plan_type", "free")
        
        # get limit, use default if not found
        if plan_type == "business":
            max_live = profile_data.get("custom_key_limit") or DEFAULT_BUSINESS_PACKAGE_MAX_LIVE_KEY_LIMIT
        else:
            max_live = PLAN_KEY_LIMITS.get(plan_type, 1)

        live_res = await asyncio.to_thread(
            lambda: supabase.table("api_keys").select("id", count="exact")
            .eq("user_id", user_id).like("key_hint", "sk_live_%").execute()
        )
        if (live_res.count or 0) >= max_live:
            logger.warning(f"action=api_key_generation_rejected | reason=max_live_keys_exceeded | plan={plan_type} | user_id={user_id}")
            raise HTTPException(status_code=403, detail={"code": "MAX_LIVE_KEYS_EXCEEDED", "message": f"API Key limit reached for {plan_type.upper()} plan. Maximum allowed count: {max_live}."})

    # create random key
    prefix = "sk_test_" if key_type == "test" else "sk_live_"
    raw_key = f"{prefix}{secrets.token_urlsafe(32)}"
    key_hint = f"{raw_key[:11]}...{raw_key[-4:]}"

    db_data = {
            "user_id": user_id,
            "key_hash": hashlib.sha256(raw_key.encode()).hexdigest(),
            "key_hint": key_hint,
            "name": name
        }

    try:
        await asyncio.to_thread(
            lambda: supabase.table("api_keys").insert(db_data).execute()
        )
        logger.info(f"action=api_key_created | type={key_type} | user_id={user_id}")
        return {
            "api_key": raw_key,
            "type": key_type,
            "message": "Save these keys safely. They cannot be read again."
        }
    except Exception as e:
        logger.error(f"action=api_key_creation_failed | user_id={user_id}", exc_info=True)
        raise HTTPException(status_code=500, detail={"code": "KEY_GENERATION_ERROR", "message": f"Error occurred while generating API key for user {current_user['id']}."})

# jwt
@app.get("/api-keys")
async def list_api_keys(current_user = Depends(management_rate_limiter)):
    user_id = current_user["id"]
    
    if current_user.get("auth_type") == "api_key":
        logger.warning(f"action=api_key_fetch_rejected | reason=invalid_auth_method | user_id={user_id}")
        raise HTTPException(status_code=403, detail={"code": "API_KEY_RESTRICTED", "message": "API keys cannot use for this endpoint. Please use jwt access."})
    
    try:
        res = await asyncio.to_thread(
            lambda: supabase.table("api_keys")
            .select("id, name, key_hint, created_at")
            .eq("user_id", user_id)
            .eq("is_active", True)
            .order("created_at", desc=True)
            .execute()
        )
        logger.info(f"action=api_keys_fetched | count={len(res.data)} | user_id={user_id}")
        return res.data
    except Exception as e:
        logger.error(f"action=api_key_fetch_failed | user_id={user_id}", exc_info=True)
        raise HTTPException(status_code=500, detail={"code": "API_KEY_FETCH_ERROR", "message": f"Could not fetch API keys."})

# jwt
@app.delete("/api-keys/{key_id}")
async def delete_api_key(key_id: str, current_user = Depends(management_rate_limiter)):
    user_id = current_user["id"]
    
    if current_user.get("auth_type") == "api_key":
        logger.warning(f"action=api_key_revoke_rejected | reason=invalid_auth_method | user_id={user_id}")
        raise HTTPException(status_code=403, detail={"code": "API_KEY_RESTRICTED", "message": "API keys cannot use for this endpoint. Please use jwt access."})
    
    try:
        await asyncio.to_thread(
            lambda: supabase.table("api_keys")
            .update({"is_active": False}) # soft delete
            .eq("id", key_id)
            .eq("user_id", user_id)
            .execute()
        )
        logger.info(f"action=api_key_revoked | key_id={key_id} | user_id={user_id}")
        return {"message": "API Key revoked successfully"}
    except Exception as e:
        logger.error(f"action=api_key_revoke_failed | key_id={key_id} | user_id={user_id}", exc_info=True)
        raise HTTPException(status_code=500, detail={"code": "API_KEY_REVOKE_ERROR", "message": f"Could not revoke API key {key_id}."})

# jwt + key
@app.post("/v1/analyze")
async def analyze_image(request: Request, file: UploadFile = File(...), auth = Depends(rate_limiter)):
    active_client_id = auth["id"]
    profile_data = auth["profile"]
    is_test_mode = auth.get("is_test", False)
    request_id = f"req_{uuid.uuid4().hex[:12]}"
    start_time = time.time()

    # file extension check
    file_name = file.filename or ""
    file_ext = os.path.splitext(file.filename)[1].lower()
    if file_ext not in ALLOWED_EXTENSIONS:
        display_ext = file_ext if file_ext else "No extension"
        logger.warning(f"action=analysis_rejected | reason=invalid_file_extension | extension={display_ext} | user_id={active_client_id}")
        await log_failed_request_to_db(active_client_id, request_id, "/v1/analyze", "INVALID_FILE_EXTENSION", f"Extension not allowed: {display_ext}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={"code": "INVALID_FILE_EXTENSION", "message": f"Allowed extensions: {ALLOWED_EXTENSIONS}"}
        )
    # mime type check
    if file.content_type not in ALLOWED_MIME_TYPES:
        logger.warning(f"action=analysis_rejected | reason=invalid_file_mime_type | mime={file.content_type} | user_id={active_client_id}")
        await log_failed_request_to_db(active_client_id, request_id, "/v1/analyze", "INVALID_FILE_MIME_TYPE", f"Mime type not allowed: {file.content_type}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={"code": "INVALID_FILE_MIME_TYPE", "message": f"Allowed mime types: {ALLOWED_MIME_TYPES}"}
        )
    # file size check
    if file.size > MAX_FILE_SIZE:
        logger.warning(f"action=analysis_rejected | reason=file_too_large | size_bytes={file.size} | user_id={active_client_id}")
        await log_failed_request_to_db(active_client_id, request_id, "/v1/analyze", "FILE_TOO_LARGE", "File size exceeds maximum limit.")
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail={"code": "FILE_TOO_LARGE", "message": f"file is too big: max size is {MAX_FILE_SIZE / (1024*1024)}MB"}
        )
    if file.size < MIN_FILE_SIZE:
        logger.warning(f"action=analysis_rejected | reason=file_too_small | size_bytes={file.size} | user_id={active_client_id}")
        await log_failed_request_to_db(active_client_id, request_id, "/v1/analyze", "FILE_TOO_SMALL", "File size is below minimum limit.")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={"code": "FILE_TOO_SMALL", "message": f"file is too small: min size is {MIN_FILE_SIZE / 1024}KB"}
        )

    if not is_test_mode:
        # check credits
        current_credits = profile_data.get("credits", 0)
        if current_credits <= 0:
            logger.warning(f"action=analysis_rejected | reason=insufficient_credits | user_id={active_client_id}")
            await log_failed_request_to_db(active_client_id, request_id, "/v1/analyze", "INSUFFICIENT_CREDITS", "Not enough credits.")
            raise HTTPException(status_code=status.HTTP_402_PAYMENT_REQUIRED, detail={"code": "INSUFFICIENT_CREDITS", "message": "Not enough credits, please do payment"})
        
        # check daily limit
        await check_daily_limit(profile=profile_data, request_id=request_id, endpoint="/v1/analyze")

    try:
        content = await file.read()
        img_matrix = decode_image(content)
        
        # checkpoint 1: image quality control
        quality_check = validate_image_quality(img_matrix)
        if not quality_check["is_valid"]:
            logger.warning(f"action=analysis_rejected | reason={quality_check['error_code'].lower()} | user_id={active_client_id}")
            await log_failed_request_to_db(active_client_id, request_id, "/v1/analyze", quality_check["error_code"], quality_check["message"])
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail={
                    "request_id": request_id,
                    "status": "failed",
                    "error": {
                        "code": quality_check["error_code"],
                        "message": quality_check["message"],
                        "recommendation": "Please ensure the image is clear, well-lit, and high resolution."
                    },
                    "meta": {
                        "credits_used": 0,
                        "credits_deducted": False,
                        "credits_remaining": profile_data.get("credits", 0),
                        "mode": "test" if is_test_mode else "live",
                        "processing_time_ms": int((time.time() - start_time) * 1000)
                    }
                }
            )

        # checkpoint 2: human face check
        try:
            face_check = await check_human_face(img_matrix)
        except Exception as face_err:
            logger.error(f"action=face_detection_failed | request_id={request_id}", exc_info=True)
            raise HTTPException(
                status_code=500, 
                detail={"code": "FACE_DETECTION_ERROR", "message": "Face detection service temporarily unavailable. No credits deducted."}
            )

        if not face_check["is_valid"]:
            logger.warning(f"action=analysis_rejected | reason={face_check['error_code'].lower()} | request_id={request_id} | user_id={active_client_id}")
            await log_failed_request_to_db(active_client_id, request_id, "/v1/analyze", face_check["error_code"], face_check["message"])
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail={
                    "request_id": request_id,
                    "status": "failed",
                    "error": {
                        "code": face_check["error_code"],
                        "message": face_check["message"],
                        "recommendation": "Please upload a clear photo of a single person. Group photos or distant shots may cause inaccurate results."
                    },
                    "meta": {
                        "credits_used": 0,
                        "credits_deducted": False,
                        "credits_remaining": profile_data.get("credits", 0), # no credits used
                        "mode": "test" if is_test_mode else "live",
                        "processing_time_ms": int((time.time() - start_time) * 1000)
                    }
                }
            )

        # ---- TEST MODE ----
        if is_test_mode:
            # gerçekçi analiz süresi simülasyonu
            await asyncio.sleep(1.2)
            test_decision = ANALYSIS_MAP["AUTHENTIC"]

            logger.info(f"action=analysis_success | mode=test | request_id={request_id} | user_id={active_client_id}")
            return {
                "request_id": request_id,
                "status": "success",
                "results": {
                    "authenticity_score": 99.00,
                    "verdict": {
                        "risk_level": test_decision["risk_level"],
                        "label": test_decision["label"]
                    },
                    "recommendation": test_decision["recommendation"],
                    "explanation": test_decision["description"],
                    "semantic_details": {
                        "semantic_anomaly_reasons": [],
                        "semantic_anomaly_breakdown": None
                    },
                    "scores": {
                        "ai_generated": 1.00,
                        "deepfake": 1.00,
                        "semantic_anomaly": 0.00
                    }
                },
                "meta": {
                    "credits_used": 0,
                    "credits_deducted": False,
                    "credits_remaining": 0,
                    "mode": "test",
                    "processing_time_ms": int((time.time() - start_time) * 1000)
                }
            }

        # sightengine
        params = {
            'models': 'genai,deepfake',
            'api_user': SIGHTENGINE_USER,
            'api_secret': SIGHTENGINE_SECRET
        }
        files = {'media': (file.filename, content, file.content_type)}

        response = await http_client.post(API_URL, data=params, files=files)
        response.raise_for_status() 
        result = response.json()

        if result.get("status") != "success":
            logger.error(f"action=sightengine_api_failed | request_id={request_id} | http_status={response.status_code}")
            raise HTTPException(status_code=400, detail={"code": "UPSTREAM_API_ERROR", "message": f"Upstream API error for request {request_id}."})
        provider_req_id = result.get("request", {}).get("id")

        genai_score = round(result.get("type", {}).get("ai_generated", 0) * 100, 2)
        deepfake_score = round(result.get("type", {}).get("deepfake", 0) * 100, 2)

        # semantic layer with vlm
        semantic_anomaly_score = None
        semantic_anomaly_reasons = None
        semantic_anomaly_explanation = None
        semantic_anomaly_details = None
        vlm_prompt_tokens = 0
        vlm_completion_tokens = 0
        openai_request_id = None

        if genai_score < 85.0 and deepfake_score < 80.0:
            vlm_start = time.time()
            vlm_response = await call_vlm(content)
            semantic_anomaly_score = vlm_response["total_anomaly_score"]
            semantic_anomaly_reasons = vlm_response["anomaly_reasons"]
            semantic_anomaly_explanation = vlm_response["anomaly_explanation"]
            semantic_anomaly_details = vlm_response["details"]
        
            vlm_prompt_tokens = vlm_response.get("prompt_tokens", 0)
            vlm_completion_tokens = vlm_response.get("completion_tokens", 0)
            openai_request_id = vlm_response.get("openai_request_id")

            logger.info(f"action=vlm_analysis_completed | request_id={request_id} | duration_sec={time.time() - vlm_start:.2f} | score={semantic_anomaly_score}")
        else:
            logger.info(f"action=vlm_skipped | reason=high_technical_confidence | request_id={request_id}")

        # calculate authenticity score
        safe_semantic_score = semantic_anomaly_score if semantic_anomaly_score is not None else 0.0
        authenticity_score = round(100.0 - max(genai_score, deepfake_score, safe_semantic_score), 2)

        # decision
        if safe_semantic_score >= 80.0: decision = ANALYSIS_MAP["SEMANTIC_ANOMALY"]
        elif deepfake_score >= 80.0: decision = ANALYSIS_MAP["DEEPFAKE"]
        elif genai_score >= 85.0: decision = ANALYSIS_MAP["SYNTHETIC"]
        elif genai_score >= 50.0: decision = ANALYSIS_MAP["MODIFIED"]
        elif safe_semantic_score >= 40.0 or deepfake_score >= 30.0 or genai_score >= 30.0: decision = ANALYSIS_MAP["INCONCLUSIVE"]
        else: decision = ANALYSIS_MAP["AUTHENTIC"]

        # storage
        unique_filename = f"{uuid.uuid4()}{file_ext}"
        file_path = f"{active_client_id}/{unique_filename}"
        await asyncio.to_thread(
            lambda: supabase.storage.from_("images").upload(file_path, content, file_options={"content-type": file.content_type})
        )

        # db insert
        db_data = {
            "user_id": active_client_id,
            "image_path": file_path,
            "genai_score": genai_score,
            "deepfake_score": deepfake_score,
            "authenticity_score": authenticity_score,
            "semantic_anomaly_score": semantic_anomaly_score,
            "semantic_anomaly_details": semantic_anomaly_details,
            "semantic_anomaly_explanation": semantic_anomaly_explanation,
            "risk_level": decision["risk_level"],
            "label": decision["label"],
            "action": decision["recommendation"]["action"],
            "user_request_id": request_id,
            "provider_request_id": provider_req_id,
            "vlm_request_id": openai_request_id
        }
        try:
            db_insert_response = await asyncio.to_thread(
                lambda: supabase.table("analysis_history").insert(db_data).execute()
            )
            if not db_insert_response.data:
                logger.error(f"action=db_insert_failed | reason=empty_data | request_id={request_id}")
                try: await asyncio.to_thread(lambda: supabase.storage.from_("images").remove([file_path]))
                except: pass
                raise HTTPException(status_code=500, detail={"code": "ANALYSIS_SAVE_ERROR", "message": f"Analysis could not be saved for request {request_id}."})
            history_id = db_insert_response.data[0]['id']
        except Exception as e:
            logger.error(f"action=db_insert_failed | reason=exception | request_id={request_id}", exc_info=True)
            try: await asyncio.to_thread(lambda: supabase.storage.from_("images").remove([file_path]))
            except: pass
            raise HTTPException(status_code=500, detail={"code": "DATABASE_CONNECTION_ERROR", "message": f"Database connection error for request {request_id}."})

        # billing logs
        try:
            pricing_res = await asyncio.to_thread(
                lambda: supabase.table("pricing_config").select("*").execute()
            )
            pricing_data = {row["model_id"]: row for row in pricing_res.data}
            gpt = pricing_data.get("gpt-4o-mini", {"input_unit_price": -1, "output_unit_price": -1, "unit_size": 1000000, "unit_type": "token"})
            se = pricing_data.get("sightengine_check_v1", {"input_unit_price": -1, "output_unit_price": -1, "unit_size": 1, "unit_type": "operation"})

            vlm_in_cost = (vlm_prompt_tokens / float(gpt["unit_size"])) * float(gpt["input_unit_price"])
            vlm_out_cost = (vlm_completion_tokens / float(gpt["unit_size"])) * float(gpt["output_unit_price"])
            se_ops = 10 # genai(5) + deepfake(5)
            se_cost = (se_ops / float(se["unit_size"])) * float(se["input_unit_price"])
            total_analysis_cost = vlm_in_cost + vlm_out_cost + se_cost

            billing_data = {
                "analysis_id": history_id,
                "vlm_input_amount_consumed": vlm_prompt_tokens,
                "vlm_output_amount_consumed": vlm_completion_tokens,
                "vlm_input_unit_price": float(gpt["input_unit_price"]),
                "vlm_output_unit_price": float(gpt["output_unit_price"]),
                "vlm_unit_size": int(gpt["unit_size"]),
                "vlm_unit_type": gpt["unit_type"],
                "vlm_input_cost": round(vlm_in_cost, 6),
                "vlm_output_cost": round(vlm_out_cost, 6),
                "se_amount_consumed": se_ops,
                "se_unit_price": float(se["input_unit_price"]),
                "se_unit_size": int(se["unit_size"]),
                "se_unit_type": se["unit_type"],
                "se_total_cost": round(se_cost, 6),
                "analysis_total_cost": round(total_analysis_cost, 6)
            }
            await asyncio.to_thread(lambda: supabase.table("billing_logs").insert(billing_data).execute())
        except Exception as b_err:
            logger.critical(f"action=billing_log_failed | analysis_id={history_id}", exc_info=True)

        # credits update via rpc
        try:
            rpc_response = await asyncio.to_thread(
                lambda: supabase.rpc("process_analysis_billing", {"user_id": active_client_id}).execute()
            )
            new_credits = rpc_response.data
        except Exception as db_err:
            logger.error(f"action=billing_rpc_failed | request_id={request_id}", exc_info=True)
            await asyncio.to_thread(
                lambda: supabase.table("analysis_history").delete().eq("id", history_id).execute()
            )
            try: supabase.storage.from_("images").remove([file_path])
            except: pass
            raise HTTPException(status_code=500, detail={"code": "BILLING_ERROR", "message": f"No credits used or daily count updated, process failed for request {request_id}."})
        
        logger.info(f"action=analysis_success | mode=live | request_id={request_id} | user_id={active_client_id} | score={authenticity_score}")
        return {
            "request_id": request_id,
            "status": "success",
            "results": {
                "authenticity_score": authenticity_score,
                "verdict": {
                    "risk_level": decision["risk_level"],
                    "label": decision["label"]
                },
                "recommendation": decision["recommendation"],
                "explanation": semantic_anomaly_explanation or decision["description"],
                "semantic_details": {
                    "semantic_anomaly_reasons": semantic_anomaly_reasons,
                    "semantic_anomaly_breakdown": semantic_anomaly_details
                } if semantic_anomaly_score is not None else None,
                "scores": {
                    "ai_generated": genai_score,
                    "deepfake": deepfake_score,
                    "semantic_anomaly": semantic_anomaly_score
                }
            },
            "meta": {
                "credits_used": 1,
                "credits_deducted": True,
                "credits_remaining": new_credits,
                "mode": "live",
                "processing_time_ms": int((time.time() - start_time) * 1000)
            }
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"action=analysis_general_error | request_id={request_id}", exc_info=True)
        raise HTTPException(status_code=500, detail={"code": "INTERNAL_ERROR", "message": f"Internal server error for request {request_id}."})

# jwt
@app.get("/history")
async def get_history(auth = Depends(management_rate_limiter)):
    active_client_id = auth["id"]
    
    if auth.get("auth_type") == "api_key":
        logger.warning(f"action=history_fetch_rejected | reason=invalid_auth_method | user_id={active_client_id}")
        raise HTTPException(status_code=403, detail={"code": "API_KEY_RESTRICTED", "message": "API keys cannot use for this endpoint. Please use jwt access."})

    try:
        # Sadece giriş yapan kullanıcıya ait verileri çek
        response = await asyncio.to_thread(
            lambda: supabase.table("analysis_history") \
                .select("*") \
                .eq("user_id", active_client_id) \
                .is_("deleted_at", "null") \
                .order("created_at", desc=True) \
                .execute()
        )

        clean_history = []
        for log in response.data:
            current_image_url = None
            saved_path = log.get("image_path")
            if saved_path and not log.get("purged_at") and not log.get("deleted_at"):
                try:
                    signed_res = await asyncio.to_thread(
                        lambda p=saved_path: supabase.storage.from_("images").create_signed_url(p, expires_in=3600)
                    )
                    current_image_url = signed_res.get("signedURL") or signed_res.get("signed_url")
                except Exception:
                    current_image_url = None

            # label üzerinden ANALYSIS_MAP'teki karşılığını bul
            decision = next((val for val in ANALYSIS_MAP.values() if val["label"] == log.get("label")), None)
            
            item = {
                "id": log.get("id"),
                "image_url": current_image_url,
                "purged_at": log.get("purged_at"),
                "purge_reason": log.get("purge_reason"),
                "authenticity_score": log.get("authenticity_score"),
                "verdict": {
                    "risk_level": log.get("risk_level"),
                    "label": log.get("label")
                },
                "recommendation": {
                    "action": log.get("action"),
                    "message": decision["recommendation"]["message"] if decision else None
                },
                "explanation": log.get("semantic_anomaly_explanation") or (decision["description"] if decision else None),
                "semantic_details": {
                    "semantic_anomaly_reasons": [k.upper() for k, v in log.get("semantic_anomaly_details").items() if v >= 80.0],
                    "semantic_anomaly_breakdown": log.get("semantic_anomaly_details")
                } if log.get("semantic_anomaly_details") else None,
                "scores": {
                    "ai_generated": log.get("genai_score"),
                    "deepfake": log.get("deepfake_score"),
                    "semantic_anomaly": log.get("semantic_anomaly_score")
                },
                "user_request_id": log.get("user_request_id"),
                "created_at": log.get("created_at")
            }
            clean_history.append(item)

        return clean_history
    except Exception as e:
        logger.error(f"action=history_fetch_failed | user_id={active_client_id}", exc_info=True)
        raise HTTPException(status_code=500, detail={"code": "INTERNAL_ERROR", "message": "Could not fetch history."})

# jwt
@app.delete("/history/{analysis_id}")
async def delete_full_analysis(analysis_id: str, auth = Depends(management_rate_limiter)):
    active_client_id = auth["id"]
    
    if auth.get("auth_type") == "api_key":
        logger.warning(f"action=analysis_delete_rejected | reason=invalid_auth_method | user_id={active_client_id}")
        raise HTTPException(status_code=403, detail={"code": "API_KEY_RESTRICTED", "message": "API keys cannot use for this endpoint. Please use jwt access."})
    
    try:
        res = await asyncio.to_thread(
            lambda: supabase.table("analysis_history")
            .select("image_path, deleted_at")
            .eq("id", analysis_id)
            .eq("user_id", active_client_id)
            .execute()
        )
        
        if not res or not getattr(res, "data", []):
            raise HTTPException(status_code=404, detail="Analysis record not found.")
            
        log = res.data[0]

        if log.get("deleted_at"):
            raise HTTPException(status_code=400, detail="Analysis record is already deleted.")

        image_path = log.get("image_path")
        now_iso = datetime.now(timezone.utc).isoformat()
        update_data = {
            "deleted_at": now_iso
        }

        if image_path:
            # görsel daha önceden silinmemişse bu alanları güncelle, silinmiş ise olduğu gibi bırak
            update_data["image_path"] = None
            update_data["purged_at"] = now_iso
            update_data["purge_reason"] = "user_delete_analysis_request"

            try:
                await asyncio.to_thread(
                    lambda p=image_path: supabase.storage.from_("images").remove([p])
                )
            except Exception as e:
                logger.error(f"action=physical_image_delete_failed | analysis_id={analysis_id} | error={str(e)}")

        await asyncio.to_thread(
            lambda: supabase.table("analysis_history")
            .update(update_data)
            .eq("id", analysis_id)
            .execute()
        )

        logger.info(f"action=analysis_soft_deleted | analysis_id={analysis_id} | user_id={active_client_id}")
        return {
            "status": "success", 
            "message": "Analysis record" + (" and associated image" if image_path else "") + " have been removed."
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"action=analysis_delete_failed | analysis_id={analysis_id} | user_id={active_client_id}", exc_info=True)
        raise HTTPException(status_code=500, detail="Internal server error during deletion.")

# jwt
@app.delete("/history/{analysis_id}/image")
async def delete_analysis_image(analysis_id: str, auth = Depends(management_rate_limiter)):
    active_client_id = auth["id"]

    if auth.get("auth_type") == "api_key":
        logger.warning(f"action=image_delete_rejected | reason=invalid_auth_method | user_id={active_client_id}")
        raise HTTPException(status_code=403, detail={"code": "API_KEY_RESTRICTED", "message": "API keys cannot use for this endpoint. Please use jwt access."})
    
    try:
        # Kaydı bul ve sahipliği kontrol et
        res = await asyncio.to_thread(
            lambda: supabase.table("analysis_history")
            .select("image_path, user_id")
            .eq("id", analysis_id)
            .eq("user_id", active_client_id)
            .execute()
        )
        
        if not res or not getattr(res, "data", []):
            raise HTTPException(status_code=404, detail="Analysis record not found.")
            
        log = res.data[0]
        image_path = log.get("image_path")

        if not image_path:
            return {"status": "ignored", "message": "Image already deleted."}

        # Storage'dan dosyayı fiziksel olarak sil
        await asyncio.to_thread(
            lambda: supabase.storage.from_("images").remove([image_path])
        )
        
        now_iso = datetime.now(timezone.utc).isoformat()
        await asyncio.to_thread(
            lambda: supabase.table("analysis_history")
            .update({
                "image_path": None,
                "purged_at": now_iso,
                "purge_reason": "user_delete_image_request"
            })
            .eq("id", analysis_id)
            .execute()
        )

        logger.info(f"action=image_manually_deleted | analysis_id={analysis_id} | user_id={active_client_id}")
        return {
            "status": "success", 
            "message": "Image permanently deleted from storage."
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"action=image_delete_failed | analysis_id={analysis_id} | user_id={active_client_id}", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred during deletion.")
    
class UserLogin(BaseModel):
    email: EmailStr
    password: str

# should be used only development for api testing, not for production
@app.post("/login", dependencies=[Depends(auth_rate_limiter)])
def login(user: UserLogin):
    try:
        # Supabase kullanıcının parolasını doğrular ve bir session döner
        response = supabase.auth.sign_in_with_password({
            "email": user.email,
            "password": user.password
        })

        # check waitlist
        user_id = response.user.id
        profile_res = supabase.table("profiles").select("is_allowed").eq("id", user_id).maybe_single().execute()
        is_allowed = profile_res.data.get("is_allowed", False) if profile_res.data else False

        logger.info(f"action=login_success | user_id={user_id} | email={user.email} | is_allowed={is_allowed}")

        return {
            "message": "login success",
            "access_token": response.session.access_token,
            "refresh_token": response.session.refresh_token,
            "token_type": "bearer",
            "is_allowed": is_allowed
        }
    except AuthApiError as e:
        error_msg = str(e)
        if "Email not confirmed" in error_msg:
            logger.warning(f"action=login_failed | reason=email_not_confirmed | email={user.email}")
            raise HTTPException(
                status_code=401, 
                detail={"code": "EMAIL_NOT_CONFIRMED", "message": "Please confirm your email address before logging in."}
            )
        logger.warning(f"action=login_failed | reason=invalid_credentials | email={user.email}")
        raise HTTPException(status_code=401, detail={"code": "INVALID_CREDENTIALS", "message": "Invalid email or password."})
    except Exception as e:
        logger.error(f"action=login_error | email={user.email}", exc_info=True)
        raise HTTPException(status_code=500, detail={"code": "LOGIN_ERROR", "message": "Internal server error."})

# jwt
@app.get("/me")
async def get_me(auth = Depends(management_rate_limiter)):
    user_id = auth.get("id")

    if auth.get("auth_type") == "api_key":
        logger.warning(f"action=profile_fetch_rejected | reason=invalid_auth_method | user_id={user_id}")
        raise HTTPException(status_code=403, detail={"code": "API_KEY_RESTRICTED", "message": "API keys cannot use for this endpoint. Please use jwt access."})
    
    profile = auth.get("profile", {})
    profile["app_metadata"] = {"provider": auth.get("provider")}
    return profile

# X-signature
@app.post("/webhook/lemonsqueezy", include_in_schema=False)
async def lemon_squeezy_webhook(request: Request):
    secret = os.getenv("LEMON_SQUEEZY_WEBHOOK_SECRET").encode('utf-8')
    signature = request.headers.get("X-Signature")
    
    if not signature:
        logger.warning("action=webhook_rejected | reason=missing_signature")
        raise HTTPException(status_code=400, detail="Missing signature")

    body = await request.body()
    
    # Güvenlik Doğrulaması
    hash_obj = hmac.new(secret, body, hashlib.sha256).hexdigest()
    if not hmac.compare_digest(hash_obj, signature):
        logger.warning("action=webhook_rejected | reason=invalid_signature")
        raise HTTPException(status_code=401, detail="Invalid signature")

    payload = json.loads(body)
    event_name = payload.get("meta", {}).get("event_name")
    custom_data = payload.get("meta", {}).get("custom_data", {})
    user_id = custom_data.get("user_id")

    if not user_id:
        logger.warning(f"action=webhook_ignored | reason=missing_user_id | event={event_name}")
        return {"status": "ignored", "reason": "user_id not found"}
    
    attributes = payload.get("data", {}).get("attributes", {})
    variant_id = str(attributes.get("variant_id"))
    billing_reason = attributes.get("billing_reason")
    sub_status = attributes.get("status")

    # BÖCEK AVI
    logger.info(f"action=webhook_received | event={event_name} | variant={variant_id} | user_id={user_id}")

    # lemon squeezy variants
    LITE_VARIANT_ID = "1490345"
    PRO_VARIANT_ID = "1490323" 
    BUSINESS_VARIANT_ID = "1490341"

    try:
        now_iso = datetime.now(timezone.utc).isoformat()
        update_data = {}

        # Mevcut veritabanı durumunu çek (Gerçek bir paket değişimi olup olmadığını anlamak için)
        db_profile = await asyncio.to_thread(
            lambda: supabase.table("profiles").select("plan_type").eq("id", user_id).maybe_single().execute()
        )
        db_plan_type = (db_profile.data or {}).get("plan_type", "free")

        # Gelen variant_id'ye göre hedef paketi belirle
        target_plan = "free"
        if variant_id == LITE_VARIANT_ID: target_plan = "lite"
        elif variant_id == PRO_VARIANT_ID: target_plan = "pro"
        elif variant_id == BUSINESS_VARIANT_ID: target_plan = "business"

        # --- EVENT YÖNETİMİ ---
        # A. Yeni Abonelik (İlk Satın Alım)
        if event_name == "subscription_created":
            if target_plan == "business":
                raw_credits = custom_data.get("custom_credits", DEFAULT_BUSINESS_PACKAGE_MONTHLY_CREDITS_LIMIT)
                try:
                    credits = int(raw_credits)
                except (ValueError, TypeError):
                    credits = DEFAULT_BUSINESS_PACKAGE_MONTHLY_CREDITS_LIMIT

                update_data = {
                    "plan_type": target_plan,
                    "credits": credits,
                    "daily_usage": 0,
                    "last_daily_usage_reset": now_iso,
                    "custom_rate_limit": custom_data.get("custom_rate_limit"),
                    "custom_rate_limit_min": custom_data.get("custom_rate_limit_min"),
                    "custom_daily_limit": custom_data.get("custom_daily_limit"),
                    "custom_key_limit": custom_data.get("custom_key_limit")
                }
            else:
                update_data = {
                    "plan_type": target_plan,
                    "credits": MONTHLY_LIMITS.get(target_plan),
                    "daily_usage": 0,
                    "last_daily_usage_reset": now_iso
                }
        
        # B. Abonelik Güncellenmesi (Kart değişimi, İptal, Upgrade/Downgrade, Resume)
        elif event_name == 'subscription_updated':
            if sub_status in ['past_due', 'unpaid']:
                # Kredi kartından para çekilemedi, free'ye düşür ve kredileri sıfırla
                update_data = {
                    "plan_type": "free", 
                    "credits": 0, 
                    "daily_usage": 0,
                    "last_daily_usage_reset": now_iso,
                    "custom_rate_limit": None,
                    "custom_rate_limit_min": None,
                    "custom_daily_limit": None,
                    "custom_key_limit": None
                }
            elif sub_status == 'cancelled':
                # İptal edildi, sadece plan tipini koru, krediler olduğu gibi kalır
                update_data = {"plan_type": target_plan}
            elif sub_status in ['active']:
                # Sadece gerçek bir paket değişikliği varsa (Upgrade/Downgrade) kredileri yenile
                if target_plan != db_plan_type and target_plan != "free":
                    if target_plan == "business":
                        raw_credits = custom_data.get("custom_credits", DEFAULT_BUSINESS_PACKAGE_MONTHLY_CREDITS_LIMIT)
                        try:
                            credits = int(raw_credits)
                        except (ValueError, TypeError):
                            credits = DEFAULT_BUSINESS_PACKAGE_MONTHLY_CREDITS_LIMIT

                        update_data = {
                            "plan_type": target_plan,
                            "credits": credits,
                            "daily_usage": 0,
                            "last_daily_usage_reset": now_iso,
                            "custom_rate_limit": custom_data.get("custom_rate_limit"),
                            "custom_rate_limit_min": custom_data.get("custom_rate_limit_min"),
                            "custom_daily_limit": custom_data.get("custom_daily_limit"),
                            "custom_key_limit": custom_data.get("custom_key_limit")
                        }
                    else:
                        update_data = {
                            "plan_type": target_plan,
                            "credits": MONTHLY_LIMITS.get(target_plan),
                            "daily_usage": 0,
                            "last_daily_usage_reset": now_iso
                        }
                else:
                    # Paket aynı (sadece kart değişti veya iptalden vazgeçildi). Kredi olduğu gibi kalır
                    update_data = {"plan_type": target_plan}

        # C. Aylık Düzenli Yenileme (Başarılı Tahsilat)
        elif event_name == 'subscription_payment_success':
            if billing_reason == 'initial':
                logger.info(f"action=webhook_ignored | reason=initial_payment_handled | user_id={user_id}")
                return {"status": "ignored", "reason": "Initial payment handled by subscription_created"}
            elif db_plan_type == "free":
                logger.info(f"action=webhook_ignored | reason=free_plan_payment | user_id={user_id}")
                return {"status": "ignored", "reason": "Free plan payment success ignored"}
            else:
                if target_plan == "business":
                    raw_credits = custom_data.get("custom_credits", DEFAULT_BUSINESS_PACKAGE_MONTHLY_CREDITS_LIMIT)
                    try:
                        credits = int(raw_credits)
                    except (ValueError, TypeError):
                        credits = DEFAULT_BUSINESS_PACKAGE_MONTHLY_CREDITS_LIMIT
                else:
                    credits = MONTHLY_LIMITS.get(target_plan)

                update_data = {
                    "plan_type": target_plan,
                    "credits": credits,
                    "daily_usage": 0,
                    "last_daily_usage_reset": now_iso
                }
        
        # D. Ödeme Başarısız / Süre Bitti / İade Edildi
        elif event_name in ['subscription_expired', 'subscription_payment_failed', 'order_refunded']:
            # Süre bitimi (expired) dışında, başarısız/iade durumlarda sıfır kredi verilir
            assigned_credits = MONTHLY_LIMITS.get("free") if event_name == 'subscription_expired' else 0
            
            update_data = {
                "plan_type": "free",
                "credits": assigned_credits,
                "daily_usage": 0,
                "last_daily_usage_reset": now_iso,
                "custom_rate_limit": None,
                "custom_rate_limit_min": None,
                "custom_daily_limit": None,
                "custom_key_limit": None
            }
        
        # Hazırlanan update_data'yı veritabanına gönder
        if update_data:
            await asyncio.to_thread(
                lambda: supabase.table("profiles")
                    .update(update_data) # <--- Kritik nokta: Elinle yazmak yerine değişkeni verdik
                    .eq("id", user_id)
                    .execute()
            )
            logger.info(f"action=webhook_processed_successfully | event={event_name} | updated_plan={update_data.get('plan_type')} | user_id={user_id}")
        else:
            # Bilinen bir event geldi ama hiçbir mantığa girmediyse BURASI KRİTİK
            if event_name in ['subscription_created', 'subscription_updated', 'subscription_payment_success']:
                logger.error(f"action=webhook_critical_error | reason=empty_update_data | event={event_name} | user_id={user_id}")
                raise HTTPException(status_code=422, detail="Update data could not be constructed")
            
        return {"status": "success"}
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"action=webhook_processing_failed | event={event_name} | user_id={user_id}", exc_info=True)
        raise HTTPException(status_code=500, detail={"code": "WEBHOOK_ERROR", "message": "Internal server error processing webhook."})