
import httpx, hashlib, os, uuid, secrets, hmac, json, time, cv2, numpy as np, mediapipe as mp, asyncio, logging

from dotenv import load_dotenv
from fastapi import FastAPI, File, UploadFile, HTTPException, Depends, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security.api_key import APIKeyHeader
from pydantic import BaseModel, EmailStr
from supabase import create_client, Client, AuthApiError
from starlette.requests import Request
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
from datetime import datetime, timezone

# logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# security
MIN_FILE_SIZE = 50 * 1024 # 50 KB (trash)
MAX_FILE_SIZE = 5 * 1024 * 1024  # 5 MB
ALLOWED_MIME_TYPES = ["image/jpeg", "image/png", "image/webp"]
ALLOWED_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}

# rate limiting
# araayüz gezintisi için rate limiting
MGMT_RATE_LIMIT_STORAGE = {}
MGMT_LIMIT_PER_MINUTE = 120

# Auth işlemleri için IP bazlı limit (Dakikada 5 deneme)
AUTH_RATE_LIMIT_STORAGE = {}
AUTH_LIMIT_PER_MINUTE = 5

# RATE_LIMIT_STORAGE ve AUTH_RATE_LIMIT_STORAGE in-memory çalışıyor. Tek bir worker ile bu durum sorun yaratmaz.
# Eğer ileride sunucuda birden fazla worker çalışacaksa her workerin kendi belleği olacağından Redis entegrasyonu yapılmalıdır.
RATE_LIMIT_STORAGE = {}
RATE_LIMIT_LOCK = asyncio.Lock()
PACKAGE_LIMITS = { # rate limit / second for packages
    "free": 1,
    "lite": 1,
    "pro": 1
}
PACKAGE_LIMITS_MINUTE = { # rate limit / minute for packages
    "free": 5,
    "lite": 20,
    "pro": 60
}

# credits
# monthly limit
MONTHLY_LIMITS = {
    "free": 50,
    "lite": 500,
    "pro": 2000
}
# daily limit
DAILY_LIMITS = {
    "free": 10,
    "lite": 75,
    "pro": 300
}

# key limits
PLAN_KEY_LIMITS = {
    "free": 1,
    "lite": 2,
    "pro": 5
}

# business package default limits, theese used if data not fount at database
DEFAULT_BUSINESS_PACKAGE_RATE_LIMIT_SECOND = 5
DEFAULT_BUSINESS_PACKAGE_RATE_LIMIT_MINUTE = 120
DEFAULT_BUSINESS_PACKAGE_DAILY_CREDITS_LIMIT = 500
DEFAULT_BUSINESS_PACKAGE_MONTHLY_CREDITS_LIMIT = 5000
DEFAULT_BUSINESS_PACKAGE_MAX_LIVE_KEY_LIMIT = 20

# decision matrix
ANALYSIS_MAP = {
    "NO_HUMAN_FACE": {
        "label": "NO_HUMAN_FACE",
        "action": "REJECT",
        "risk_level": "LOW",
        "description": "The system could not detect a clear human face in the image.",
        "recommendation": "Please upload a clear profile photo containing a real human face."
    },
    "DEEPFAKE": {
        "label": "DEEPFAKE_DETECTION",
        "action": "REJECT",
        "risk_level": "HIGH",
        "description": "High probability of synthetic face swap or digital identity manipulation detected.",
        "recommendation": "High security risk. Reject the profile photo."
    },
    "SYNTHETIC": {
        "label": "SYNTHETIC_CONTENT",
        "action": "REJECT",
        "risk_level": "HIGH",
        "description": "High probability that the identity or image is entirely generated by artificial intelligence.",
        "recommendation": "High security risk. Reject the profile photo."
    },
    "MODIFIED": {
        "label": "MODIFIED_CONTENT",
        "action": "REVIEW",
        "risk_level": "MEDIUM",
        "description": "Significant digital retouching, heavy filters, or background manipulation detected. The core identity appears intact.",
        "recommendation": "Manual verification is recommended, or prompt the user for an unfiltered photo."
    },
    "INCONCLUSIVE": {
        "label": "INCONCLUSIVE",
        "action": "REVIEW",
        "risk_level": "MEDIUM",
        "description": "Image quality, compression, or file structure is insufficient for a conclusive authenticity analysis.",
        "recommendation": "Request a high-resolution, uncompressed photo taken directly from the device camera."
    },
    "AUTHENTIC": {
        "label": "AUTHENTIC",
        "action": "ACCEPT",
        "risk_level": "LOW",
        "description": "No synthetic face swap or fully AI-generated identity was detected.",
        "recommendation": "Meets identity verification standards. Acceptable."
    }
}

app = FastAPI(title="checkai b2b api", version="1.0.0")

load_dotenv()

# cors
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

# Sightengine cradentials
SIGHTENGINE_USER = os.getenv("SIGHTENGINE_USER")
SIGHTENGINE_SECRET = os.getenv("SIGHTENGINE_SECRET")
API_URL = os.getenv("API_URL")

# Supabase cradentials
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# authentication (b2b priority)
security = HTTPBearer(auto_error=False)
api_key_header = APIKeyHeader(name="X-API-KEY", auto_error=False)

# global http client
http_client = httpx.AsyncClient(
    http2=False, # Kararlılık için HTTP/1.1
    limits=httpx.Limits(max_keepalive_connections=10, max_connections=20),
    timeout=httpx.Timeout(10.0)
)

# tflite modeli yolu
MODEL_PATH = 'blaze_face_short_range.tflite'

# start the model globally
try:
    base_options = python.BaseOptions(model_asset_path=MODEL_PATH)
    options = vision.FaceDetectorOptions(
        base_options=base_options, 
        min_detection_confidence=0.5
    )
    face_detector = vision.FaceDetector.create_from_options(options)
    logger.info("MediaPipe Face Detector loaded successfully.")
except Exception as e:
    logger.critical(f"FATAL: MediaPipe model could not be loaded: {e}")
    raise RuntimeError(f"Model load failure: {e}")

async def has_human_face(image_bytes: bytes) -> bool:
    """
        Numpy 2.0+ ve en güncel MediaPipe sürümleriyle uyumlu, 
        'image_ptr' hatasını engelleyen modern implementasyon.
    """
    try:
        # byte verisini Numpy dizisine çevir
        # .copy() eklenmezse MediaPipe '_image_ptr' hatası fırlatır.
        nparr = np.frombuffer(image_bytes, np.uint8).copy()
        img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
        
        if img is None:
            return False
            
        # MediaPipe RGB formatı bekler
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        # KRİTİK ADIM: Numpy dizisinin hafıza düzenini (memory layout) zorla düzeltiyoruz
        # Bu satır, MediaPipe'ın beklediği C-style hafıza dizilimini garanti eder.
        img_rgb = np.ascontiguousarray(img_rgb)

        # MediaPipe Image objesini oluştur
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=img_rgb)
        
        # CPU bloklanmasını önlemek için asenkron thread kullan
        detection_result = await asyncio.to_thread(face_detector.detect, mp_image)
    
        # Sonuçlarda yüz var mı kontrol et
        if len(detection_result.detections) > 0:
            return True
        return False
        
    except Exception as e:
        logger.error("Face detection engine failed", exc_info=True)
        raise RuntimeError("Face detection engine failed") from e

async def get_auth_user(api_key: str = Depends(api_key_header), credentials: HTTPAuthorizationCredentials = Depends(security)):
    user_id = None
    auth_info = {}
    
    # API Key
    if api_key:
        api_key = api_key.strip()
        hashed_key = hashlib.sha256(api_key.encode()).hexdigest()

        # supabase sorgusunu ayrı bir thread ile yapıyoruz, böylece saniye bazlı rate limit uygulayabiliriz
        result = await asyncio.to_thread(
            lambda: supabase.table("api_keys").select("user_id").eq("key_hash", hashed_key).eq("is_active", True).execute()
        )

        if result.data:
            user_id = result.data[0]["user_id"]
            auth_info = {"id": user_id, "is_test": api_key.startswith("sk_test_"), "auth_type": "api_key"}
            logger.info(f"api-key accepted. key-hash: {hashed_key}")
        else:
            logger.warning(f"Invalid or inactive API key attempt. key-hash: {hashed_key}")
            raise HTTPException(status_code=401, detail={"error_code": "INVALID_API_KEY", "message": "Invalid or inactive API key."})
    # JWT
    elif credentials:
        try:
            user_response = await asyncio.to_thread(
                lambda: supabase.auth.get_user(credentials.credentials)
            )
            user_id = user_response.user.id
            auth_info = {"id": user_id, "is_test": False, "auth_type": "jwt"}
            logger.info(f"jwt accepted: user: {user_id}")
        except Exception as e:
            logger.warning(f"Invalid JWT attempt: {str(e)}")
            raise HTTPException(status_code=401, detail={"error_code": "INVALID_JWT", "message": "Invalid or expired token."})
    
    if user_id:
        # tüm profil verisi burada çekilip endpointlere dağıtılıyor
        profile_res = await asyncio.to_thread(
            lambda: supabase.table("profiles").select("*").eq("id", user_id).maybe_single().execute()
        )
        # profile_res objesi var mı ve hata içermiyor mu?
        if not profile_res or hasattr(profile_res, "error") and profile_res.error:
            logger.error(f"Supabase connection error for user {user_id}")
            raise HTTPException(status_code=500, detail="Database connection failed.")
        
        # Veri (data) var mı? .data özelliği Supabase response'unda her zaman bulunur ama boşsa None döner.
        profile = getattr(profile_res, "data", None)

        if not profile:
            logger.error(f"Data Integrity Error: Authenticated user {user_id} has no profile entry!")
            raise HTTPException(
                status_code=404, 
                detail={"error_code": "PROFILE_NOT_FOUND", "message": "Kullanıcı profili bulunamadı."}
            )
        
        # waitlist check
        if not profile.get("is_allowed", False):
            logger.warning(f"Waitlist access denied: User {user_id} is waiting for approval.")
            raise HTTPException(
                status_code=403, 
                detail={"error_code": "WAITLIST_REQUIRED", "message": "Erişim izniniz bulunmuyor."}
            )
        
        auth_info["profile"] = profile
        return auth_info

    # unauthorized
    logger.warning("Unauthorized API access attempt.")
    raise HTTPException(status_code=401, detail={"error_code": "UNAUTHORIZED", "message": "unauthorized."})

# register ve login endpointleri için limiter
async def auth_rate_limiter(request: Request):
    ip = request.client.host
    async with RATE_LIMIT_LOCK:
        now = time.time()
        if ip not in AUTH_RATE_LIMIT_STORAGE:
            AUTH_RATE_LIMIT_STORAGE[ip] = []
        
        # 60 saniyeden eski kayıtları temizle
        AUTH_RATE_LIMIT_STORAGE[ip] = [t for t in AUTH_RATE_LIMIT_STORAGE[ip] if now - t < 60.0]
        
        if len(AUTH_RATE_LIMIT_STORAGE[ip]) >= AUTH_LIMIT_PER_MINUTE:
            logger.warning(f"IP based rate limit exceeded for: {ip}")
            raise HTTPException(
                status_code=429, 
                detail="Too many attempts. Please try again in a minute."
            )
            
        AUTH_RATE_LIMIT_STORAGE[ip].append(now)

# arayüz gezintisi için rate limiter
async def management_rate_limiter(auth = Depends(get_auth_user)):
    user_id = auth["id"]
    
    async with RATE_LIMIT_LOCK:
        now = time.time()
        if user_id not in MGMT_RATE_LIMIT_STORAGE:
            MGMT_RATE_LIMIT_STORAGE[user_id] = []
        
        # Son 60 saniyeyi tut
        MGMT_RATE_LIMIT_STORAGE[user_id] = [t for t in MGMT_RATE_LIMIT_STORAGE[user_id] if now - t < 60.0]
        
        if len(MGMT_RATE_LIMIT_STORAGE[user_id]) >= MGMT_LIMIT_PER_MINUTE:
            logger.warning(f"Management rate limit exceeded for user: {user_id}")
            raise HTTPException(status_code=429, detail="Too many dashboard requests. Please slow down.")
            
        MGMT_RATE_LIMIT_STORAGE[user_id].append(now)
        
    return auth

# planlara özel rate limiter
async def rate_limiter(auth = Depends(get_auth_user)):
    user_id = auth["id"]
    profile = auth["profile"]
    plan_type = profile.get("plan_type", "free")
    
    # 1. Limit Belirleme
    if plan_type == "business":
        sec_limit = profile.get("custom_rate_limit") or DEFAULT_BUSINESS_PACKAGE_RATE_LIMIT_SECOND
        minute_limit = profile.get("custom_rate_limit_min") or DEFAULT_BUSINESS_PACKAGE_RATE_LIMIT_MINUTE
    else:
        sec_limit = PACKAGE_LIMITS.get(plan_type, 1)
        minute_limit = PACKAGE_LIMITS_MINUTE.get(plan_type, 5)

    # 2. Limit Kontrolü
    async with RATE_LIMIT_LOCK:
        now = time.time()

        if user_id not in RATE_LIMIT_STORAGE:
            RATE_LIMIT_STORAGE[user_id] = []
        
        # Temizlik: 60 saniyeden eski tüm istekleri bellekten at
        RATE_LIMIT_STORAGE[user_id] = [t for t in RATE_LIMIT_STORAGE[user_id] if now - t < 60.0]
        all_requests = RATE_LIMIT_STORAGE[user_id]

        # A. Saniyelik Kontrol (Son 1 saniye)
        requests_last_sec = [t for t in all_requests if now - t < 1.0]
        if len(requests_last_sec) >= sec_limit:
            logger.warning(f"Rate limit(second) exceeded for user: {user_id}")
            raise HTTPException(status_code=429, detail="Rate limit(seconds) exceeded")
        
        # B. Dakikalık Kontrol (Son 60 saniye)
        if len(all_requests) >= minute_limit:
            logger.warning(f"Rate limit(minute) exceeded for user: {user_id}")
            raise HTTPException(status_code=429, detail=f"Exceeded minute limit: ({minute_limit} req/min).")
            
        # İstek başarılı, zaman damgasını ekle
        RATE_LIMIT_STORAGE[user_id].append(now)

    # Endpoint'in kullanması için auth datayı geri dön
    return auth

async def check_daily_limit(profile: dict):
    user_id = profile.get("id")
    daily_usage = profile.get("daily_usage", 0)
    last_reset_str = profile.get("last_daily_usage_reset")
    plan_type = profile.get("plan_type", "free")

    if plan_type == "business":
        daily_limit = profile.get("custom_daily_limit") or DEFAULT_BUSINESS_PACKAGE_DAILY_CREDITS_LIMIT
    else:
        daily_limit = DAILY_LIMITS.get(plan_type)

    now = datetime.now(timezone.utc)
    
    # 24 Saat Kontrolü ve Sıfırlama
    if not last_reset_str:
        last_reset_str = now.isoformat()
        
    last_reset = datetime.fromisoformat(last_reset_str.replace('Z', '+00:00'))
    
    if (now - last_reset).total_seconds() >= 86400:
        daily_usage = 0
        await asyncio.to_thread(
            lambda: supabase.table("profiles")
            .update({"daily_usage": 0, "last_daily_usage_reset": now.isoformat()})
            .eq("id", user_id).execute()
        )

    # Limit Aşım Kontrolü
    if daily_usage >= daily_limit:
        logger.warning(f"Daily limit exceeded for user: {user_id}")
        raise HTTPException(
            status_code=429, 
            detail=f"Daily usage limit exceeded: max = {daily_limit}."
        )
    
    return daily_usage

# jwt
@app.post("/generate-api-key")
async def generate_api_key(name: str = "Default Key", key_type: str = "live", current_user = Depends(rate_limiter)):
    if current_user.get("auth_type") == "api_key":
        raise HTTPException(status_code=403, detail="API keys cannot be used for management endpoints. Please use jwt access.")
    
    user_id = current_user["id"]

    # test key: max 1 for every user
    if key_type == "test":
        test_res = await asyncio.to_thread(
            lambda: supabase.table("api_keys").select("id", count="exact")
            .eq("user_id", user_id).like("key_hint", "sk_test_%").execute()
        )
        if (test_res.count or 0) >= 1:
            raise HTTPException(status_code=403, detail="Max allowed test key count = 1")
    
    # live key
    else:
        profile_data = current_user.get("profile", {})
        plan_type = profile_data.get("plan_type", "free")
        
        # get limit, use default if not found
        if plan_type == "business":
            max_live = profile_data.get("custom_key_limit") or DEFAULT_BUSINESS_PACKAGE_MAX_LIVE_KEY_LIMIT
        else:
            max_live = PLAN_KEY_LIMITS.get(plan_type, 1)

        live_res = await asyncio.to_thread(
            lambda: supabase.table("api_keys").select("id", count="exact")
            .eq("user_id", user_id).like("key_hint", "sk_live_%").execute()
        )
        if (live_res.count or 0) >= max_live:
            raise HTTPException(status_code=403, detail=f"API Key limit reached for {plan_type.upper()} plan. Maximum allowed count: {max_live}.")

    # create random key
    prefix = "sk_test_" if key_type == "test" else "sk_live_"
    raw_key = f"{prefix}{secrets.token_urlsafe(32)}"
    key_hint = f"{raw_key[:11]}...{raw_key[-4:]}"

    db_data = {
            "user_id": user_id,
            "key_hash": hashlib.sha256(raw_key.encode()).hexdigest(),
            "key_hint": key_hint,
            "name": name
        }

    try:
        await asyncio.to_thread(
            lambda: supabase.table("api_keys").insert(db_data).execute()
        )
        logger.info(f"New API key generated for user: {current_user['id']}")
        return {
            "api_key": raw_key,
            "type": key_type,
            "message": "Save these keys safely. They cannot be read again."
        }
    except Exception as e:
        logger.error(f"Key generation error for user {current_user['id']}", exc_info=True)
        raise HTTPException(status_code=500, detail="Key generation error")

# jwt
@app.get("/api-keys")
async def list_api_keys(current_user = Depends(management_rate_limiter)):
    if current_user.get("auth_type") == "api_key":
        raise HTTPException(status_code=403, detail="API keys cannot be used for management endpoints. Please use jwt access.")
    
    user_id = current_user["id"]
    
    try:
        res = await asyncio.to_thread(
            lambda: supabase.table("api_keys")
            .select("id, name, key_hint, created_at")
            .eq("user_id", user_id)
            .eq("is_active", True)
            .order("created_at", desc=True)
            .execute()
        )
        return res.data
    except Exception as e:
        logger.error(f"Error fetching API keys for user {user_id}", exc_info=True)
        raise HTTPException(status_code=500, detail="Could not fetch API keys")

# jwt
@app.delete("/api-keys/{key_id}")
async def delete_api_key(key_id: str, current_user = Depends(rate_limiter)):
    if current_user.get("auth_type") == "api_key":
        raise HTTPException(status_code=403, detail="API keys cannot be used for management endpoints. Please use jwt access.")
    
    user_id = current_user["id"]
    
    try:
        await asyncio.to_thread(
            lambda: supabase.table("api_keys")
            .update({"is_active": False}) # soft delete
            .eq("id", key_id)
            .eq("user_id", user_id)
            .execute()
        )
        return {"message": "API Key revoked successfully"}
    except Exception as e:
        logger.error(f"Error revoking API key {key_id} for user {user_id}", exc_info=True)
        raise HTTPException(status_code=500, detail="Could not revoke API key")

# jwt + key
@app.post("/v1/analyze")
async def analyze_image(request: Request, file: UploadFile = File(...), auth = Depends(rate_limiter)):
    active_client_id = auth["id"]
    profile_data = auth["profile"]
    is_test_mode = auth.get("is_test", False)
    request_id = f"req_{uuid.uuid4().hex[:12]}"
    start_time = time.time()

    # ---- TEST MODE ----
    if is_test_mode:
        # gerçekçi analiz süresi simülasyonu
        await asyncio.sleep(1.2)
        
        logger.info(f"Test analysis successful - Request: {request_id}, User: {active_client_id}")
        return {
            "request_id": request_id,
            "status": "success",
            "results": {
                "verdict": {"action": "ACCEPT","risk_level": "LOW","label": "AUTHENTIC"},
                "summary": {
                    "description": "No synthetic face swap or fully AI-generated identity was detected (Test Mode).",
                    "recommendation": "Meets identity verification standards. Acceptable."
                },
                "scores": {"ai_generated": 0.01,"deepfake": 0.01}
            },
            "meta": {
                "credits_used": 0,
                "credits_deducted": False,
                "credits_remaining": "unlimited (test mode)",
                "processing_time_ms": int((time.time() - start_time) * 1000)
            }
        }

    # file extension check
    file_ext = os.path.splitext(file.filename)[1].lower()
    if file_ext not in ALLOWED_EXTENSIONS:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"unallowed file extension! Allowed extensions: {ALLOWED_EXTENSIONS}"
        )
    # mime type check
    if file.content_type not in ALLOWED_MIME_TYPES:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="unallowed file mime type"
        )
    # file size check
    if file.size > MAX_FILE_SIZE:
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail=f"file is too big: max size is {MAX_FILE_SIZE / (1024*1024)}MB"
        )
    if file.size < MIN_FILE_SIZE:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"file is too small: min size is {MIN_FILE_SIZE}KB"
        )

    # check credits
    current_credits = profile_data.get("credits", 0)

    if current_credits <= 0:
        logger.warning(f"Insufficient credits for user: {active_client_id}")
        raise HTTPException(
            status_code=status.HTTP_402_PAYMENT_REQUIRED,
            detail="Not enough credits, please do payment"
        )
    
    # --- GÜNLÜK LİMİT KONTROLÜ ---
    await check_daily_limit(profile_data)

    try:
        content = await file.read()
        
        try:
            is_human = await has_human_face(content)
        except Exception as face_err:
            logger.error(f"Face detection error for request {request_id}", exc_info=True)
            raise HTTPException(
                status_code=500, 
                detail={"error": "Face detection service temporarily unavailable. No credits deducted."}
            )

        # pre-checkpoint 1: if no human face
        if not is_human:
            logger.info(f"No human face found - Request: {request_id}, User: {active_client_id}. No credits deducted.")
            decision = ANALYSIS_MAP["NO_HUMAN_FACE"]
            return {
                "request_id": request_id,
                "status": "success",
                "results": {
                    "verdict": {
                        "action": decision["action"],
                        "risk_level": decision["risk_level"],
                        "label": decision["label"]
                    },
                    "summary": {
                        "description": decision["description"],
                        "recommendation": decision["recommendation"]
                    },
                    "scores": {"ai_generated": 0.0, "deepfake": 0.0}
                },
                "meta": {
                    "credits_used": 0,
                    "credits_deducted": False,
                    "credits_remaining": current_credits, # no credits used
                    "processing_time_ms": int((time.time() - start_time) * 1000)
                }
            }

        # sightengine
        params = {
            'models': 'genai,deepfake',
            'api_user': SIGHTENGINE_USER,
            'api_secret': SIGHTENGINE_SECRET
        }
        files = {'media': (file.filename, content, file.content_type)}

        response = await http_client.post(API_URL, data=params, files=files)
        response.raise_for_status() 
        result = response.json()

        if result.get("status") != "success":
            logger.error(f"Sightengine API error for request {request_id}: {result}")
            raise HTTPException(status_code=400, detail={"request_id": request_id, "error": "Upstream API error"})

        genai_score = result.get("type", {}).get("ai_generated", 0)
        deepfake_score = result.get("type", {}).get("deepfake", 0)
        provider_req_id = result.get("request", {}).get("id")

        # decision
        if deepfake_score >= 0.80: decision = ANALYSIS_MAP["DEEPFAKE"]
        elif genai_score >= 0.85: decision = ANALYSIS_MAP["SYNTHETIC"]
        elif 0.50 <= genai_score < 0.85: decision = ANALYSIS_MAP["MODIFIED"]
        elif 0.30 <= deepfake_score < 0.80 or 0.30 <= genai_score < 0.50: decision = ANALYSIS_MAP["INCONCLUSIVE"]
        else: decision = ANALYSIS_MAP["AUTHENTIC"]

        # Resmi Storage'a yükle ve URL al, dosya isimlerini unique yap
        file_extension = file.filename.split(".")[-1]
        unique_filename = f"{uuid.uuid4()}.{file_extension}"
        file_path = f"{active_client_id}/{unique_filename}"
        supabase.storage.from_("images").upload(file_path, content, file_options={"content-type": file.content_type})
        image_url = supabase.storage.from_("images").get_public_url(file_path)

        # db insert
        db_data = {
            "user_id": active_client_id,
            "image_url": image_url,
            "genai_score": genai_score,
            "deepfake_score": deepfake_score,
            "risk_level": decision["risk_level"],
            "label": decision["label"],
            "action": decision["action"],
            "user_request_id": request_id,
            "provider_request_id": provider_req_id
        }
        try:
            db_insert_response = await asyncio.to_thread(
                lambda: supabase.table("analysis_history").insert(db_data).execute()
            )
            # empty result
            if not db_insert_response.data:
                logger.error(f"Database insertion failed (Empty Data) for request {request_id}")
                # clear
                try: await asyncio.to_thread(lambda: supabase.storage.from_("images").remove([file_path]))
                except: pass
                raise HTTPException(status_code=500, detail="Analysis could not be saved.")
            history_id = db_insert_response.data[0]['id']
        except Exception as e:
            logger.error(f"Database technical exception for request {request_id}: {str(e)}")
            try: await asyncio.to_thread(lambda: supabase.storage.from_("images").remove([file_path]))
            except: pass
            raise HTTPException(status_code=500, detail="Database connection error.")

        # güvenli kredi düşme ve günlük sayaç artırma
        try:
            rpc_response = await asyncio.to_thread(
                lambda: supabase.rpc("process_analysis_billing", {"user_id": active_client_id}).execute()
            )
            new_credits = rpc_response.data
        except Exception as db_err:
            logger.error(f"Billing/DB transaction failed for request {request_id}", exc_info=True)
            # İşlem DB seviyesinde reddedildi, eklenen çöp verileri temizle
            await asyncio.to_thread(
                lambda: supabase.table("analysis_history").delete().eq("id", history_id).execute()
            )
            try: supabase.storage.from_("images").remove([file_path])
            except: pass
            raise HTTPException(status_code=500, detail={"request_id": request_id, "error": "Kredi düşülmedi veya günlük sayaç artırılamadı, işlem iptal edildi."})
        
        logger.info(f"Analysis success - Request: {request_id}, User: {active_client_id}")
        return {
            "request_id": request_id,
            "status": "success",
            "results": {
                "verdict": {
                    "action": decision["action"],
                    "risk_level": decision["risk_level"],
                    "label": decision["label"]
                },
                "summary": {
                    "description": decision["description"],
                    "recommendation": decision["recommendation"]
                },
                "scores": {
                    "ai_generated": genai_score,
                    "deepfake": deepfake_score
                }
            },
            "meta": {
                "credits_used": 1,
                "credits_deducted": True,
                "credits_remaining": new_credits,
                "processing_time_ms": int((time.time() - start_time) * 1000)
            }
        }
    except Exception as e:
        logger.error(f"Analysis general error for request {request_id}", exc_info=True)
        raise HTTPException(status_code=500, detail={"request_id": request_id, "error": str(e)})

# jwt
@app.get("/history")
async def get_history(auth = Depends(management_rate_limiter)):
    if auth.get("auth_type") == "api_key":
        raise HTTPException(status_code=403, detail="API keys cannot read history. Please use jwt access.")

    active_client_id = auth["id"]

    try:
        # Sadece giriş yapan kullanıcıya ait verileri çek
        response = await asyncio.to_thread(
            lambda: supabase.table("analysis_history") \
                .select("*") \
                .eq("user_id", active_client_id) \
                .order("created_at", desc=True) \
                .execute()
        )
        return response.data
    except Exception as e:
        logger.error(f"History fetch error for user {active_client_id}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Database error: {str(e)}")

class UserRegister(BaseModel):
    email: EmailStr
    password: str

# will deprecated soon
@app.post("/register", dependencies=[Depends(auth_rate_limiter)])
def register(user: UserRegister):
    try:
        # Supabase auth modülü parolayı kendisi şifreler
        response = supabase.auth.sign_up({
            "email": user.email,
            "password": user.password
        })

        if response.user is None:
            raise HTTPException(
                status_code=400,
                detail="User could not be created"
            )

        logger.info(f"Register success for user: {user.email}")
        return {
            "message": "user register success for " + user.email, 
            "user": response.user
        }
    except Exception as e:
        logger.error(f"Register error for {user.email}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))
    
class UserLogin(BaseModel):
    email: EmailStr
    password: str

# will deprecated soon
@app.post("/login", dependencies=[Depends(auth_rate_limiter)])
def login(user: UserLogin):
    try:
        # Supabase kullanıcının parolasını doğrular ve bir session döner
        response = supabase.auth.sign_in_with_password({
            "email": user.email,
            "password": user.password
        })

        # check waitlist
        user_id = response.user.id
        profile_res = supabase.table("profiles").select("is_allowed").eq("id", user_id).maybe_single().execute()
        is_allowed = profile_res.data.get("is_allowed", False) if profile_res.data else False

        logger.info(f"Login success for user: {user.email} - Allowed: {is_allowed}")

        return {
            "message": "login success",
            "access_token": response.session.access_token,
            "refresh_token": response.session.refresh_token,
            "token_type": "bearer",
            "is_allowed": is_allowed
        }
    except AuthApiError as e:
        logger.warning(f"Invalid login attempt for {user.email}")
        raise HTTPException(status_code=401, detail=str(e.message))
    except Exception as e:
        logger.error(f"Login error for {user.email}", exc_info=True)
        raise HTTPException(status_code=500, detail="Internal server error")

# jwt
@app.get("/me")
async def get_me(auth = Depends(management_rate_limiter)):
    if auth.get("auth_type") == "api_key":
        raise HTTPException(status_code=403, detail="API keys cannot read history. Please use jwt access.")
    
    return auth.get("profile", {})

# X-signature
@app.post("/webhook/lemonsqueezy", include_in_schema=False)
async def lemon_squeezy_webhook(request: Request):
    secret = os.getenv("LEMON_SQUEEZY_WEBHOOK_SECRET").encode('utf-8')
    signature = request.headers.get("X-Signature")
    
    if not signature:
        logger.warning("Webhook signature verification failed.")
        raise HTTPException(status_code=400, detail="Missing signature")

    body = await request.body()
    
    # Güvenlik Doğrulaması
    hash_obj = hmac.new(secret, body, hashlib.sha256).hexdigest()
    if not hmac.compare_digest(hash_obj, signature):
        logger.warning("Webhook signature verification failed.")
        raise HTTPException(status_code=401, detail="Invalid signature")

    payload = json.loads(body)
    event_name = payload.get("meta", {}).get("event_name")
    custom_data = payload.get("meta", {}).get("custom_data", {})
    user_id = custom_data.get("user_id")

    if not user_id:
        logger.info(f"Webhook received but user_id missing. Payload: {payload}")
        return {"status": "ignored", "reason": "user_id not found"}
    
    attributes = payload.get("data", {}).get("attributes", {})
    variant_id = str(attributes.get("variant_id"))
    billing_reason = attributes.get("billing_reason")

    # BÖCEK AVI
    logger.info(f"Webhook received - Event: {event_name}, Variant: {variant_id}, User: {user_id}")

    # lemon squeezy variants
    LITE_VARIANT_ID = "1490345"
    PRO_VARIANT_ID = "1490323" 
    BUSINESS_VARIANT_ID = "1490341"

    try:
        now_iso = datetime.now(timezone.utc).isoformat()

        # Veritabanına gönderilecek ana paket
        update_data = {}

        # 1. Yeni kayıt, paket yükseltme/düşürme veya aylık yenileme (Krediyi ve Günlük Kullanımı setler)
        if event_name in ['subscription_created', 'subscription_updated', 'subscription_payment_success']:
            # Durum A: Variant ID varsa (Yeni Abonelik / Paket Değişimi)
            if variant_id in [LITE_VARIANT_ID, PRO_VARIANT_ID, BUSINESS_VARIANT_ID]:
                if variant_id == LITE_VARIANT_ID: 
                    plan_type = "lite"
                    credits = MONTHLY_LIMITS.get(plan_type)
                elif variant_id == PRO_VARIANT_ID: 
                    plan_type = "pro"
                    credits = MONTHLY_LIMITS.get(plan_type)
                elif variant_id == BUSINESS_VARIANT_ID:
                    plan_type = "business"
                    credits = int(custom_data.get("custom_credits", DEFAULT_BUSINESS_PACKAGE_MONTHLY_CREDITS_LIMIT))
                    # Business'a özel limitleri custom_data'dan çek ve ekle
                    update_data.update({
                        "custom_rate_limit": custom_data.get("custom_rate_limit"),
                        "custom_rate_limit_min": custom_data.get("custom_rate_limit_min"),
                        "custom_daily_limit": custom_data.get("custom_daily_limit"),
                        "custom_key_limit": custom_data.get("custom_key_limit")
                    })

            # Durum B: Variant ID yok ama Ödeme Başarılı ise (Aylık Düzenli Yenileme)
            elif event_name == 'subscription_payment_success':
                # İlk satın alma işleminde krediler subscription_created ile verildiği için bunu yoksay
                if billing_reason == 'initial':
                    return {"status": "ignored", "reason": "Initial payment handled by subscription_created"}
                
                db_profile = await asyncio.to_thread(
                    lambda: supabase.table("profiles").select("plan_type").eq("id", user_id).maybe_single().execute()
                )
                profile_data = db_profile.data or {}
                plan_type = profile_data.get("plan_type", "free")
                
                if plan_type == "free":
                    return {"status": "ignored", "reason": "Free plan payment success ignored"}
        
                if plan_type == "business":
                    credits = int(custom_data.get("custom_credits", DEFAULT_BUSINESS_PACKAGE_MONTHLY_CREDITS_LIMIT))
                else:
                    credits = MONTHLY_LIMITS.get(plan_type)

            # Durum C: Variant ID yok ve ödeme başarılı eventi değilse
            else:
                logger.warning(f"Webhook skipped - Event: {event_name}, Variant: {variant_id}")
                return {"status": "ignored", "reason": "Missing or unknown variant_id"}
            
            # Ortak güncellenecek alanları update_data'ya ekle
            update_data.update({
                "plan_type": plan_type,
                "credits": credits,
                "daily_usage": 0,
                "last_daily_usage_reset": now_iso
            })
            
        # 2. Abonelik süresi tamamen bittiğinde (Free plana düşürür)
        elif event_name == 'subscription_expired':
            update_data = {
                "plan_type": "free",
                "credits": MONTHLY_LIMITS.get("free"),
                "daily_usage": 0,
                "last_daily_usage_reset": now_iso,
                # Business'tan düşüyorsa özel limitleri temizle (isteğe bağlı)
                "custom_rate_limit": None,
                "custom_rate_limit_min": None,
                "custom_daily_limit": None,
                "custom_key_limit": None
            }

        # 3. İade veya İptal durumunda
        elif event_name in ['order_refunded']:
            update_data = {
                "plan_type": "free",
                "credits": 0,
                "daily_usage": 0,
                "last_daily_usage_reset": now_iso
            }
        
        # Hazırlanan update_data'yı veritabanına gönder
        if update_data:
            await asyncio.to_thread(
                lambda: supabase.table("profiles")
                    .update(update_data) # <--- Kritik nokta: Elinle yazmak yerine değişkeni verdik
                    .eq("id", user_id)
                    .execute()
            )
            logger.info(f"Successfully updated profile for user {user_id}")
        else:
            # Bilinen bir event geldi ama hiçbir mantığa girmediyse BURASI KRİTİK
            if event_name in ['subscription_created', 'subscription_updated', 'subscription_payment_success']:
                logger.error(f"CRITICAL: Payment event received but update_data is empty! Payload: {payload}")
                raise HTTPException(status_code=422, detail="Update data could not be constructed")
            
        return {"status": "success"}
    
    except Exception as e:
        logger.error("Webhook processing error", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))